//constante utilizada para manter conformidade entre legenda de formulario e feedback em erros

export const contratoLabels = {
    departamento: "Unidade Requisitante",
    licitacao_modelo_id: "",
    licitacao_modelo: "Modalidade de licitação",
    envio_material_tecnico: "Envio material técnico",
    minuta_edital: "Minuta edital",
    abertura_certame: "Abertura certame",
    homologacao: "Homologação",
    processo_sei: "Processo SEI",
    credor: "Credor",
    dotacao_orcamentaria: "",
    cnpj_cpf: "CNPJ/CPF",
    tipo_objeto: "Tipo de objeto",
    objeto: "Objeto",
    numero_contrato: "Nº Contrato / Nota de Empenho Inicial",
    data_assinatura: "Data de assinatura",
    valor_contrato: "Valor",
    valor_mensal_estimativo: "Valor mensal estimativo",
    data_inicio_vigencia: "Início da Vigência",
    data_vencimento: "Data de vencimento",
    condicao_pagamento: "Condição de Pagamento",
    prazo_a_partir_de: "Prazo a partir de",
    numero_nota_reserva: "Número nota reserva",
    valor_reserva: "Valor reserva",
    nome_empresa: "Nome da empresa",
    telefone_empresa: "Telefone da empresa",
    email_empresa: "E-mail da empresa",
    outras_informacoes: "Informações adicionais",
}